/**
 * Autogenerated sine tables. See tools/ax25_lookup/ax25_lookup.py
 */

#ifndef AX25_SINTABLE_H
#define AX25_SINTABLE_H


#include "samd20.h"

#define AX25_SINTABLE_ORDER 9
#define AX25_SINTABLE_LENGTH 512


/**
 * 1st quadrant sin lookup table for 1.5kHz deviation
 *
 * Length: 512
 * Frequency Resolution: 7.805 Hz
 */
uint16_t sintable_512_1500hz[512];

/**
 * 1st quadrant sin lookup table for 2.5kHz deviation
 *
 * Length: 512
 * Frequency Resolution: 7.805 Hz
 */
uint16_t sintable_512_2500hz[512];

#endif /* AX25_SINTABLE_H */
