/**
 * Autogenerated no_aprs structures. See sim/geofence
 */

#ifndef GEOFENCE_NO_APRS_H
#define GEOFENCE_NO_APRS_H


#include <stdbool.h>

#include "samd20.h"

const int16_t* no_aprs_outlines[27];
const uint16_t no_aprs_outline_lengths[27];

#endif /* GEOFENCE_NO_APRS_H */
