/**
 * Autogenerated aprs zone structures. See sim/geofence
 */

#ifndef GEOFENCE_APRS_H
#define GEOFENCE_APRS_H


#include <stdbool.h>

#include "samd20.h"


/**
 * struct representing all we need to know about a aprs zone
 */
struct aprs_zone_t {
  int32_t** outlines;
  uint32_t* outline_lengths;
  int32_t frequency, deviation;
  char* name;
};


struct aprs_zone_t aprs_zones[12];

#endif /* GEOFENCE_APRS_H */
