/**
 * Autogenerated no_aprs structures. See sim/geofence
 */

#ifndef GEOFENCE_NO_APRS_H
#define GEOFENCE_NO_APRS_H


#include <stdbool.h>

#include "samd20.h"

const int32_t* no_aprs_outlines[36];
const uint32_t no_aprs_outline_lengths[36];

#endif /* GEOFENCE_NO_APRS_H */
