/**
 * Autogenerated aprs zone structures. See sim/geofence
 */

#ifndef GEOFENCE_APRS_ZONES_H
#define GEOFENCE_APRS_ZONES_H


#include <stdbool.h>

#include "samd20.h"


/**
 * struct representing all we need to know about a aprs zone
 */
struct aprs_zone_t {
  const int32_t** outlines;
  const uint32_t outline_count;
  const uint32_t* outline_lengths;
  int32_t frequency, deviation;
  char* name;
};


const struct aprs_zone_t aprs_zones[11];

#endif /* GEOFENCE_APRS_ZONES_H */
