/**
 * Autogenerated telemetry structures. See sim/geofence
 */

#ifndef GEOFENCE_TELEMETRY_H
#define GEOFENCE_TELEMETRY_H


#include <stdbool.h>

#include "samd20.h"

const int32_t* telemetry_outlines[14];
const uint32_t telemetry_outline_lengths[14];

#endif /* GEOFENCE_TELEMETRY_H */
