/**
 * Autogenerated country structures. See sim/geofence
 */

#ifndef GEOFENCE_COUNTRIES_H
#define GEOFENCE_COUNTRIES_H


#include <stdbool.h>

#include "samd20.h"


/**
 * struct representing all we need to know about a country
 */
struct country_t {
  int32_t** outlines;
  char* name;
  char* isocode;
  bool data_tx, aprs_tx;
};


struct country_t countries[];

#endif /* GEOFENCE_COUNTRIES_H */
