/**
 * Autogenerated country structures. See sim/geofence
 */

#ifndef GEOFENCE_COUNTRIES_H
#define GEOFENCE_COUNTRIES_H


#include <stdbool.h>

#include "samd20.h"


/**
 * struct representing all we need to know about a country
 */
struct country_t {
  const int32_t** outlines;
  const uint32_t* outline_lengths;
  char* name;
  char* isocode;
  bool data_tx, aprs_tx;
};


const struct country_t countries[233];

#endif /* GEOFENCE_COUNTRIES_H */
