/**
 * Autogenerated telemetry structures. See sim/geofence
 */

#ifndef GEOFENCE_TELEMETRY_H
#define GEOFENCE_TELEMETRY_H


#include <stdbool.h>

#include "samd20.h"

const int16_t* const telemetry_outlines[5];
const uint16_t telemetry_outline_lengths[5];

#endif /* GEOFENCE_TELEMETRY_H */
